services:
  db:
    image: mysql:8.0
    container_name: center_ferramentas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: center_ferramentas_backend
    ports:
      - "8000:80"
    volumes:
      - ./backend/src:/var/www/html
      - ./backend/assets:/var/www/html/assets
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      APP_URL: ${REACT_APP_API_URL}

  frontend:
    build: ./frontend
    container_name: center_ferramentas_frontend
    ports:
      - "3030:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      WATCHPACK_POLLING: "true"

volumes:
  db_data:
